### ISSUE TITLE
NATNET FRAME TIMEOUT When running mocap_helper.launch

### ISSUE THREAD

**Issue by LZMHIT** [USC-ACTLab/crazyswarm#103] opened 2018-10-09 09:20 UTC
Dear Author, 
  I am so sorry to bother you again, but I am so confused with the system that I can not make any progress in my work. As for the question I asked in #90 ,I found that I need to modify the Local interface ip address in the Optitrack SW. Like following pictures.
![503fcd677827b751636c9cd0b306999](https://user-images.githubusercontent.com/23434354/46658897-5e4fba00-cbe6-11e8-8ea8-75feb37142d8.png)
However,I meet another problem. I launch the mocap_helper.launch again, and I got this messages
![wrong](https://user-images.githubusercontent.com/23434354/46659040-b38bcb80-cbe6-11e8-95d0-609f0d7b421a.png)
It flashed with the same message. And no topics are pub.
![wrong1](https://user-images.githubusercontent.com/23434354/46659334-56dce080-cbe7-11e8-879a-e642e6e722c3.png)
And I have another Question, Do I need to turn on the crazyflie2.0 and plug in the CrazyRadio when I just launch the mocap_helper.launch file?
I really hope to receive your replay, Thank you so much.

**Comment by whoenig** [comment] 2018-10-09 16:30
mocap_helper does not use the crazyflie/crazyradio, so no need to plug anything else in. Unfortunately, the qualisys effort is community-driven and I haven't tested the system myself, so I am not sure what the issue is.

**Comment by whoenig** [comment] 2018-12-07 23:37
Closing this issue, see issue #122 for more discussions on this.

**Closed by whoenig** 2018-12-07 23:37 UTC
