### ISSUE TITLE
Installation of Vicon SDK

### ISSUE THREAD

**Issue by Pop99** [USC-ACTLab/crazyswarm#66] opened 2018-06-10 13:22 UTC
Hi,
I'm new to linux, but in following the Crazyswarm installation, cant seem to match up the vicon SDK installation path with the structure downloaded. I don't have the following path

ros_ws/src/crazyflie_ros/externalDependencies/libmotioncapture/externalDependencies/vicon_sdk 

There is a slightly different externalDependencies path but this seems to have an "error opening directory", pics attached.

Would appreciate any help

![cf structure 1](https://user-images.githubusercontent.com/24283106/41201940-62db255a-6cb9-11e8-9f90-636c7b29d3d1.png)
![cf structure 2](https://user-images.githubusercontent.com/24283106/41201942-66402a88-6cb9-11e8-8d0c-248fec80a4f2.png)
![cf structure 3](https://user-images.githubusercontent.com/24283106/41201943-696da3de-6cb9-11e8-9863-2928808cafce.png)

**Comment by whoenig** [comment] 2018-06-12 01:12
The SDK should be put in `ros_ws/src/externalDependencies/libmotioncapture/externalDependencies/vicon_sdk`.

**Comment by Pop99** [comment] 2018-06-12 08:48
Thank you, this is new ground for me, but I'm looking forward to running this.
I have put the SDK in this position. Looking at other posts I believe I may have to run the catkin_make -k command before I run the ./build.sh command (both from the home/po78/crazyswarm/ros_ws directory).
When I do the catkin command I get this
![v1](https://user-images.githubusercontent.com/24283106/41279740-33339f4a-6e25-11e8-951c-b9a26453b280.png)
![v2](https://user-images.githubusercontent.com/24283106/41279754-38a9d0c0-6e25-11e8-9211-370417bb7056.png)
![v3](https://user-images.githubusercontent.com/24283106/41279758-3d73183c-6e25-11e8-82b1-f1116e974f03.png)

**Comment by whoenig** [comment] 2018-06-13 18:44
libobjecttracker is a git submodule. It should be automatically checked out if you run `./build.sh` in the crazyswarm root folder. The `catkin_make -k` should not be needed anymore (this was essentially a bug in our build dependencies).

**Comment by Pop99** [comment] 2018-06-13 20:43
Hi, have just run ./build.sh from the /home/po78/crazyswarm directory with the following results
Start of run
![v5](https://user-images.githubusercontent.com/24283106/41376356-e9a6e29c-6f50-11e8-8515-67138228fc0f.png)
End of run
![v9](https://user-images.githubusercontent.com/24283106/41376439-26577eae-6f51-11e8-8bc7-cb147f634623.png)

[CMakeOutput.log](https://github.com/USC-ACTLab/crazyswarm/files/2099806/CMakeOutput.log)

[CMakeError.log](https://github.com/USC-ACTLab/crazyswarm/files/2099807/CMakeError.log)

Unsure of the reported issue

**Comment by Pop99** [comment] 2018-06-13 21:30
It looks like libobjecttracker isn't being made available, is there a workaround?
Would really like to get onto next step if poss, thanks

**Comment by whoenig** [comment] 2018-06-14 02:14
It should be pulled by `./build.sh` [here](https://github.com/USC-ACTLab/crazyswarm/blob/master/build.sh#L4-L5). Can you type those lines manually and see if you get any error?

**Comment by Pop99** [comment] 2018-06-14 08:54
Please see commands manually typed from crazyswarm directory below

po78@DESKTOP-4VH4RF8:~/crazyswarm$ # submodules
po78@DESKTOP-4VH4RF8:~/crazyswarm$ git submodule init
po78@DESKTOP-4VH4RF8:~/crazyswarm$ git submodule update
fatal: destination path 'ros_ws/src/externalDependencies/libmotioncapture' already exists and is not an empty directory.
fatal: clone of 'https://github.com/USC-ACTLab/libmotioncapture.git' into submodule path 'ros_ws/src/externalDependencies/libmotioncapture' failed
po78@DESKTOP-4VH4RF8:~/crazyswarm$

Middle set of commands seem ok but the Command
catkin_make -DCMAKE_BUILD_TYPE=RelWithDebInfo -k

results in 

po78@DESKTOP-4VH4RF8:~/crazyswarm/ros_ws$ catkin_make -DCMAKE_BUILD_TYPE=RelWithDebInfo -k
Base path: /home/po78/crazyswarm/ros_ws
Source space: /home/po78/crazyswarm/ros_ws/src
Build space: /home/po78/crazyswarm/ros_ws/build
Devel space: /home/po78/crazyswarm/ros_ws/devel
Install space: /home/po78/crazyswarm/ros_ws/install
####
#### Running command: "cmake /home/po78/crazyswarm/ros_ws/src -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_DEVEL_PREFIX=/home/po78/crazyswarm/ros_ws/devel -DCMAKE_INSTALL_PREFIX=/home/po78/crazyswarm/ros_ws/install -G Unix Makefiles" in "/home/po78/crazyswarm/ros_ws/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/po78/crazyswarm/ros_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/po78/crazyswarm/ros_ws/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.11
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 8 packages in topological order:
-- ~~  - crazyflie (metapackage)
-- ~~  - crazyflie_controller
-- ~~  - crazyflie_cpp
-- ~~  - crazyflie_description
-- ~~  - crazyflie_tools
-- ~~  - crazyflie_demo
-- ~~  - crazyflie_driver
-- ~~  - crazyswarm
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'crazyflie'
-- ==> add_subdirectory(crazyflie_ros/crazyflie)
-- +++ processing catkin package: 'crazyflie_controller'
-- ==> add_subdirectory(crazyflie_ros/crazyflie_controller)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'crazyflie_cpp'
-- ==> add_subdirectory(crazyflie_ros/crazyflie_cpp)
Using ROS (catkin_make)
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on '/usr/lib/x86_64-linux-gnu/libusb-1.0.so' but
  neither '/usr/lib/x86_64-linux-gnu/libusb-1.0.so_INCLUDE_DIRS' nor
  '/usr/lib/x86_64-linux-gnu/libusb-1.0.so_LIBRARIES' is defined.
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  crazyflie_ros/crazyflie_cpp/ROS.cmake:18 (catkin_package)
  crazyflie_ros/crazyflie_cpp/CMakeLists.txt:6 (include)


-- +++ processing catkin package: 'crazyflie_description'
-- ==> add_subdirectory(crazyflie_ros/crazyflie_description)
-- +++ processing catkin package: 'crazyflie_tools'
-- ==> add_subdirectory(crazyflie_ros/crazyflie_tools)
Using ROS (catkin_make)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
-- +++ processing catkin package: 'crazyflie_demo'
-- ==> add_subdirectory(crazyflie_ros/crazyflie_demo)
-- +++ processing catkin package: 'crazyflie_driver'
-- ==> add_subdirectory(crazyflie_ros/crazyflie_driver)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- crazyflie_driver: 7 messages, 11 services
-- +++ processing catkin package: 'crazyswarm'
-- ==> add_subdirectory(crazyswarm)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "libobjecttracker"
  with any of the following names:

    libobjecttrackerConfig.cmake
    libobjecttracker-config.cmake

  Add the installation prefix of "libobjecttracker" to CMAKE_PREFIX_PATH or
  set "libobjecttracker_DIR" to a directory containing one of the above
  files.  If "libobjecttracker" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  crazyswarm/CMakeLists.txt:7 (find_package)


-- Could not find the required component 'libobjecttracker'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "libobjecttracker"
  with any of the following names:

    libobjecttrackerConfig.cmake
    libobjecttracker-config.cmake

  Add the installation prefix of "libobjecttracker" to CMAKE_PREFIX_PATH or
  set "libobjecttracker_DIR" to a directory containing one of the above
  files.  If "libobjecttracker" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  crazyswarm/CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/po78/crazyswarm/ros_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/po78/crazyswarm/ros_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by Pop99** [comment] 2018-06-14 09:53
Please excuse the guess, but should there be something like 

cd ros_ws/src/externalDependencies/libmotioncapture/
git submodule init
git submodule update
cd $ROOT

for the 'libobjecttracker' module in the build.sh or do the object tracker files come in another way?

**Comment by whoenig** [comment] 2018-06-14 16:16
I think the problem is here:

> po78@DESKTOP-4VH4RF8:/crazyswarm$ git submodule update
> fatal: destination path 'ros_ws/src/externalDependencies/libmotioncapture' already exists and is not an empty directory.
> fatal: clone of 'https://github.com/USC-ACTLab/libmotioncapture.git' into submodule path 'ros_ws/src/externalDependencies/libmotioncapture' failed
> po78@DESKTOP-4VH4RF8:/crazyswarm$

Simply delete the (empty?) `ros_ws/src/externalDependencies/libmotioncapture` folder and run ./build.sh again. I am not sure why you have an (empty?) folder there.

The other portion is only needed for modules that have submodule themselves (or, one could recursively checkout, but that adds some additional unnecessary items.)

**Comment by Pop99** [comment] 2018-06-14 20:08
I've deleted the libmotioncapture directory which does let it build alot little further, but there is a reference to vicon_sdk/DataStreamClient.h which it is expecting to find in one of the subdirectories we just deleted. So I think there is a mismatch somewhere along the line between the build structure and the file structure. 
![v10](https://user-images.githubusercontent.com/24283106/41435224-1036506c-7016-11e8-9b45-ba5218c01406.png)
![v11](https://user-images.githubusercontent.com/24283106/41435241-19a5d97e-7016-11e8-8523-93063a990c9e.png)

Could the below comment be a mistake, i'm not sure it fits with the procedure for step 2

The SDK should be put in ros_ws/src/externalDependencies/libmotioncapture/externalDependencies/vicon_sdk.

Thanks for your continuing support, I'll get there.

**Comment by Pop99** [comment] 2018-06-14 20:28
In Vicon.cpp there is an 'include' call to get the DataStreamClient.h file from vicon_sdk

#include "libmotioncapture/vicon.h"
// VICON
#include "vicon_sdk/DataStreamClient.h"

using namespace ViconDataStreamSDK::CPP;

Not sure we have a vicon_sdk at this point, because if it exists in the subdirectory of externalDependencies the build script wont work as we have found

**Comment by whoenig** [comment] 2018-06-14 21:07
The include folder is added in the CMakeFile (see https://github.com/USC-ACTLab/libmotioncapture/blob/8d2386c7ce99c095b54e5d9898a3263119fbd245/CMakeLists.txt#L32). 

Make sure to put the sdk in the right folder and that you have the files that are indicated in the documentation (http://crazyswarm.readthedocs.io/en/latest/installation.html#simulation-and-physical-robots). If it doesn't work, provide an output of `tree` in `ros_ws/src/externalDependencies/libmotioncapture/externalDependencies/vicon_sdk`.

**Comment by Pop99** [comment] 2018-06-15 07:31
Tried lots of options, but at the moment the SDK is situated as below as per instructions on http://crazyswarm.readthedocs.io/en/latest/installation.html

![v12](https://user-images.githubusercontent.com/24283106/41454710-548a0f9a-7072-11e8-9fbe-5978b5730464.png)

As far as
ros_ws/src/externalDependencies/libmotioncapture/externalDependencies/vicon_sdk (Its not there)

I believe this particular libmotioncapture structure is generated by the ./build.sh run from the crazyswarm directory. If the structure exists before we run ./build.sh then it will complain about the libmotioncapture directory existing. I don't think we can add the sdk here after the build script is run.



This is what I currently have for this structure

![v13](https://user-images.githubusercontent.com/24283106/41455100-d9580334-7073-11e8-9fc4-77b404d4c6a6.png)

and this is what  i currently get when the build script is run

![v11](https://user-images.githubusercontent.com/24283106/41455784-434b60cc-7076-11e8-9dfc-4243f3049fbf.png)

**Comment by Pop99** [comment] 2018-06-15 08:09
Quick question about your comment below if I may

The include folder is added in the CMakeFile (see https://github.com/USC-ACTLab/libmotioncapture/blob/8d2386c7ce99c095b54e5d9898a3263119fbd245/CMakeLists.txt#L32).

Doesent this reference the below directory

![v14](https://user-images.githubusercontent.com/24283106/41457385-614390ea-707b-11e8-9c4e-4417c7b7f8e2.png)

![v15](https://user-images.githubusercontent.com/24283106/41457405-6fcd4d86-707b-11e8-9cd3-181bc2c17593.png)

Along with the other NatNetLinux structures etc?

**Comment by Pop99** [comment] 2018-06-16 12:49
Thank you Wolfgang,
The build seems to have completed with no red error messages so I'm hoping all's ok to continue.

**Comment by YimingWan** [comment] 2018-06-25 20:05
Hi Pop99 and whoenig,
We have been running into very similar problems when trying to run the ./build.sh. We are unsure of where to put the vicon SDK files (DataStreamClient.h, libboost_system-mt.so.1.58.0, and libboost_thread-mt.so.1.58.0) once they have been downloaded. No matter where we seem to put them, we always run into some variation of the error " Invoking "make -j8 -l8" failed ". We usually reach about 90% on the build before it "cannot find -lViconDataStreamSDK_CPP" (or some variation). 
Below are some screenshots of our errors.

![part1](https://user-images.githubusercontent.com/14075700/41872954-7906e768-7891-11e8-87ec-46ea196e7ace.png)
![part2](https://user-images.githubusercontent.com/14075700/41872955-7916eeba-7891-11e8-930d-5f395e69e39c.png)
![part3](https://user-images.githubusercontent.com/14075700/41872956-7923d102-7891-11e8-9f7c-5bd18f0fe3d1.png)

Thanks for any help you can give!

**Comment by whoenig** [comment] 2018-06-25 20:10
The output of the tree command on how it should look like is given here: http://crazyswarm.readthedocs.io/en/latest/installation.html#simulation-and-physical-robots. Basically, don't use the 20170125_... subfolder at all and put the header file in a subfolder that you have to create (include\vicon_sdk).

**Comment by whoenig** [comment] 2018-12-07 23:38
vicon_sdk is now open source and a submodule of the crazyswarm. Closing.

**Closed by whoenig** 2018-12-07 23:38 UTC

**Comment by stevedanomodolor** [comment] 2022-04-23 17:27
I added this in the crazyswam cmakelist 

```
add_subdirectory(externalDependencies/libmotioncapture EXCLUDE_FROM_ALL)
add_subdirectory(externalDependencies/libobjecttracker EXCLUDE_FROM_ALL)
```
